name: Convert Markdown to HTML

on:
  push:
    branches:
      - main  # Run on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check for Changes in Markdown Folder
      id: check_changes
      run: |
        # Check for any differences in the markdown folder
        if git diff --quiet HEAD^ HEAD -- markdown; then
          echo "No changes in the markdown folder"
          echo "changed=false" >> $GITHUB_ENV
        else
          echo "Changes detected in the markdown folder"
          echo "changed=true" >> $GITHUB_ENV
        fi

    - name: Set up Python
      if: env.changed == 'true'  # Only run if there are changes
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: env.changed == 'true'  # Only run if there are changes
      run: |
        pip install markdown

    - name: Convert Markdown to HTML
      if: env.changed == 'true'  # Only run if there are changes
      run: |
        python scripts/convert_md_to_html.py

    - name: Create or Update Pull Request
      if: env.changed == 'true'  # Only run if there are changes
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Add generated HTML files"
        branch: update-html
        base: main
        title: "Add generated HTML files"
        body: "This pull request was automatically created by GitHub Actions to add generated HTML files."
        delete-branch: true
