name: Convert Markdown to HTML

on:
  push:
    branches:
      - main  # Run on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install markdown

    - name: Convert Markdown to HTML
      run: |
        mkdir -p html
        for file in markdown/*.md; do
          filename=$(basename "$file" .md)
          python -c "import markdown, sys; print(markdown.markdown(sys.stdin.read()))" < "$file" > html/"$filename".html
        done
        ls html  # Check if files are correctly created in the html directory

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b update-html || git checkout update-html
        git add html/*.html  # Add only files from the html directory
        git commit -m "Add generated HTML files" || echo "No changes to commit"

    - name: Push changes to the update-html branch
      run: |
        git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" update-html

    - name: Create or Update Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-html
        base: main
        title: "Add generated HTML files"
        body: "This pull request was automatically created by GitHub Actions to add generated HTML files."
        delete-branch: true

    - name: Upload HTML files as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-files
        path: html
