name: Convert Markdown to HTML

on:
  push:
    branches:
      - main  # Run on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install markdown

    - name: Run Markdown to HTML Conversion
      run: |
        python scripts/convert_md_to_html.py

    - name: Create or Update Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Add generated HTML files"
        branch: update-html
        base: main
        title: "Add generated HTML files"
        body: "This pull request was automatically created by me, gitaction bot, because you changed your repo :)"
        delete-branch: true
