name: Convert Markdown to HTML

on:
  push:
    branches:
      - main  # Run on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install markdown

    - name: Convert Markdown to HTML
      run: |
        mkdir -p html
        for file in markdown/*.md; do
          filename=$(basename "$file" .md)
          python -c "import markdown, sys; print(markdown.markdown(sys.stdin.read()))" < "$file" > html/"$filename".html
        done
        ls html  # List files in the html directory for verification

    - name: Create or Update Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Add generated HTML files"
        branch: update-html
        base: main
        title: "Add generated HTML files"
        body: "This pull request was automatically created by GitHub Actions to add generated HTML files."
        delete-branch: true
